development:
  sessions:
    default:
      database: til_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: til_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
